### PR TITLE
Bump version to rebuild AMI

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request bumps the version for the purpose of rebuilding the AMI.

## 💭 Motivation and context ##

The old AMI is getting long in the tooth and should be refreshed.

## 🧪 Testing ##

All automated tests pass. I also built a new staging AMI and verified that it functions as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.
- [x] Build and test a staging AMI with these changes.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Comment by jsf9k** [comment]
@dav3r - I don't think this AMI is used in [cisagov/cool-assessment-terraform](https://github.com/cisagov/cool-assessment-terraform), and offhand I don't see an easy way to spin one up and test it.  Do you remember where this AMI is used?

**Comment by dav3r** [comment]
> @dav3r - I don't think this AMI is used in [cisagov/cool-assessment-terraform](https://github.com/cisagov/cool-assessment-terraform), and offhand I don't see an easy way to spin one up and test it. Do you remember where this AMI is used?

We use that AMI for our [PenTest Portal instances](https://github.com/cisagov/cool-assessment-terraform/blob/56e174bdb54a08313f03ba7e8a023a4753e01c7a/pentestportal_ec2.tf#L1-L10), so if you want to spin one up, that's how to do it.  Reminder: the PTP code is still manually deployed on to those instances by the assessors.

**Review by dav3r — APPROVED** [review]
🤯

**Comment by jsf9k** [comment]
> We use that AMI for our [PenTest Portal instances](https://github.com/cisagov/cool-assessment-terraform/blob/56e174bdb54a08313f03ba7e8a023a4753e01c7a/pentestportal_ec2.tf#L1-L10), so if you want to spin one up, that's how to do it. Reminder: the PTP code is still manually deployed on to those instances by the assessors.

I don't know how I missed that.  Thank you.

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Pull request merged**
